### PR TITLE
[BUGFIX] Remove whitespace around the email salutation

### PR DESCRIPTION
**Pull request by christophlehmann**

### CODE REVIEW

**Comment by oliverklee** [comment]
@christophlehmann Thanks for providing the PR!

Why would there be whitespace around the label?

**Comment by christophlehmann** [comment]
Our case is: `$titlexy am 17.10.2019 von 14:00 bis 15:00 .`

**Comment by oliverklee** [comment]
Oh, it looks like in that case the label "h" after "15:00" is missing. This is strange. Did you remove or unset that label? Otherwise, this might be a bug.

**Comment by christophlehmann** [comment]
Without heaving a look, in that case it should be possible to clear the label and the view ist okay :)

**Pull request closed without merging**
