### PR TITLE
[FEATURE] Add TCE validation hook to event model

### PR DESCRIPTION
**Pull request by mk-mxp**
This hook requires the return of complex data. I chose a merged array for that, as it is the most flexible solution I could think of. All hooks registered get the same parameters, and the resulting arrays are merged and return to the caller.

I will add the CHANGELOG line when it is ready to merge.

### CODE REVIEW

**Comment by oliverklee** [comment]
I'll write tests for the TCEforms hook class very soon and move the TCEforms processing from the old event model class into the TCEforms hook class. Please let's postpone this feature until then.

For the time being, I propose having the hook validation refactoring in a separate PR so we can get that in first (and this PR here will become smaller).

**Comment by oliverklee** [comment]
(The test failure is due to formatting problems in the tests.)

**Comment by mk-mxp** [comment]
Please drop a line when I can add the hook to the new TCEforms hook class.

**Comment by oliverklee** [comment]
> Please drop a line when I can add the hook to the new TCEforms hook class.

This should be in `OliverKlee\Seminars\Hooks\DataHandlerHook`.

**Comment by mk-mxp** [comment]
Just to be sure I understand your request:

I shall now implement my hook in `DataHandlerHook::processSingleEvent()` (just before `->saveToDatabase()`) and `Tx_Seminars_OldModel_Event::getUpdateArray()` stays as it is?

Or do you tell me where to expect your future changes to the TCE validation process and I shall wait for them?

**Comment by oliverklee** [comment]
I recommend you wait until I have covered the class with tests and refactored it, and then implement your hook in `DataHandlerHook::processSingleEvent()`.

**Comment by oliverklee** [comment]
@mk-mxp I have just finished moving all TCEforms data processing from the old event model to the DataHandler hook class now. So now the is road to continuing on this PR is unblocked for you. :-)

**Comment by mk-mxp** [comment]
Need to finish some CI re-working, will do that next week. Thanks for info!

**Comment by oliverklee** [comment]
@mk-mxp I hope you are well. I'm looking forward to the next version of this PR!

**Comment by oliverklee** [comment]
This PR also now has some merge conflicts. Could you please rebase and resolve the conflicts? Thanks!

**Comment by mk-mxp** [comment]
Just to keep You informed: This is on hold for another 2 weeks. Looking forward to getting this done quickly then. Thanks for Your patience, and stay in good health!

**Pull request closed without merging**
