### PR TITLE
Extbase: Events List

### PR DESCRIPTION
**Pull request by aschmutt**
Wie besprochen, der erste Extbase Controller nur mit dem List View.

### CODE REVIEW

**Comment by oliverklee** [comment]
This needs to be covered with tests: unit tests for the controller and functional tests for the mapper. Please let's do the mapper changes in a separate PR. I'll take care of porting the existing mapper changes to `nimut/testing-framework`.

**Comment by aschmutt** [comment]
Shall I wait for the testframework setup, or is it there already? 
It would be really helpfull if you could create the empty Test class at the right place for me, as I am not used to the Testing conventions and folder structures.

**Comment by oliverklee** [comment]
> Shall I wait for the testframework setup, or is it there already?

Yes, it's already there (in master).

**Comment by oliverklee** [comment]
I will switch the default branch of this repository from `master` to `main` in a minutes. As this will remove the target branch of this PR, GitHub will autoclose the PR. Could you please open a new PR (from the same branch) so the changes do not get lost?

This is how to update your local copy of the repository:
```bash
git fetch origin && git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main
```

**Pull request closed without merging**
