### PR TITLE
[TASK] Solves: Mails - recognized to be spam - Sender and receiver of…

### PR DESCRIPTION
**Pull request by samamedick**
… notification mail are the same #127

### CODE REVIEW

**Comment by oliverklee** [comment]
Hi @samamedick Thanks a lot for the PR! ❤️ I'll have a look at it now.

**Comment by oliverklee** [comment]
Hi @samamedick, some comments on the general approach:

- I propose we get create a method `RegistrationManager::getEmailSender($event)` that has the logic of finding out the sender.

- I suggest we rename the `Sender` model to `SystemSender` so the name is more descriptive.

- Please don't use return type hinting or scalar type hinting as the extension still needs to support PHP 5.6.

- I suggest we move the getting of the system email name and address directly into the `SystemSender` model.

- Please also add the new configuration option to the reference section in the manual.

- For new files, please add yourself as an  `@author`, not other persons. :-)

- Please also cover the new class and the changed code with unit tests.

- Please also add a new line to the changelog files (newest on top).

Looking forward to hearing your thoughts on this, and to the updated PR!

**Comment by oliverklee** [comment]
@samamedick Any news on this PR?

**Comment by samamedick** [comment]
@moment searching for time ;-). Will do a new PR when i'am able to fullfill all your requests.

**Comment by oliverklee** [comment]
@samamedick, are you still planing to work on this?

The oelib extension now provides helpful functions for this: https://github.com/oliverklee/ext-oelib/pull/181

I propose you use a similar approach for this like in the realty extension: https://github.com/oliverklee/ext-realty/commit/ad26a87dfaf11c41188e0ff56e7cbbe0e617c11a

**Comment by samamedick** [comment]
Sorry about the late response. Not received the notifications. I close the pull request.

**Pull request closed without merging**
