### PR TITLE
[FEATURE] Add BE registrations list hook

### PR DESCRIPTION
**Pull request by mk-mxp**
After: #238

Allows hooking into the BE registration list.

### CODE REVIEW

**Comment by oliverklee** [comment]
Oh, and please let's move the `HookService` into the `Hooks` namespace out of the `Service` namespace. (Services are kind of a catch-all, and it's easy to put things in there, but hard to find something there.)

**Comment by mk-mxp** [comment]
Tests: These are in no way new tests, they were just private to me until now. I have no experience with nimut/testing-framework, and if You are OK with me putting my old tests into `Tests/LegacyUnit/` I would be very glad.

**Comment by mk-mxp** [comment]
Line length: I am used to strict PSR-2 formatting, which states "SHOULD NOT be longer than 80 chars" and "MUST NOT be longer than 120 chars". So 80 is my destination length and 120 is an exception.

**Comment by oliverklee** [comment]
> Line length: […] So 80 is my destination length and 120 is an exception.

That's perfectly fine.

**Comment by oliverklee** [comment]
> I have no experience with `nimut/testing-framework`, and if You are OK with me putting my old tests into `Tests/LegacyUnit/` I would be very glad.

For new tests in existing test files, that's okay. For new test files, please use `nimut/testing-framework`. The tests in `Tests/Unit/` and `Tests/Functional/` already use it. At least the unit tests will work without much setup:
1. `composer install` (in the extension root directory)
2. `composer ci:tests:unit`

For the functional tests, you will need to have a test database.

If you need help getting started with the tests, please chat me up on Slack so I can help.

**Pull request closed without merging**
