### PR TITLE
[BUGFIX] Update the documentation of the hooks

### LINKED ISSUE #125: Hooks implemented according to the manual raise an exception in Typo3 8.7.
Everything worked as expected in Typo3 7.6. (and so did the implementation of `Tx_Seminars_Interface_Hook_EventListView`) but the following exception is raised in Typo3 8.7.15 now:

`#1301928334: The class Tx_Seminars_FrontEnd_DefaultController is used for the event list view hook, but does not implement the \Tx_Seminars_Interface_Hook_EventListView interface. `

The deprecation.log in Typo3 7.6. gives the following information:
`The persistent functionality of getUserObj(), prepending the class name with & is deprecated since TYPO3 CMS 7 and will be removed in TYPO3 CMS 8. To allow this functionality, implement  the \TYPO3\CMS\Core\SingletonInterface in the class "EXT:custom_ext/Classes/Hooks/ListView.php:&ListView" instead.`

### PR DESCRIPTION
**Pull request by oliverklee**
Fixes #125

[ci skip]

### CODE REVIEW

**Comment by oliverklee** [comment]
@djangones Could you please have a look whether the documentation now is at it should be? Thanks!

**Comment by djangones** [comment]
I'm not very familiar with call semantics, but I think I switched my hook classes to using namespaces because it didn't work in the way you suggested.

With namespaces, my reference call looks like this:
```
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['seminars']['singleView'][]
    = \VendorName\ExtName\Hooks\SingleView::class;
```
and the changed class definition itself looks like this:
```
namespace \VendorName\ExtName\Hooks;

class ListView extends \Tx_Seminars_Model_Event implements \Tx_Seminars_Interface_Hook_EventListView, \TYPO3\CMS\Core\SingletonInterface
```

I hope the above information helps...

**Comment by oliverklee** [comment]
@djangones Thanks for the feedback! I'll adapt the docs to use the `::class` syntax.

Does it also work for if you drop the `(implements) \TYPO3\CMS\Core\SingletonInterface` part from your class definition?

**Comment by djangones** [comment]
Yes, I just tested it quickly and implementing the SingletonInterface does not seem to be necessary.

I don't remember exactly why I introduced it, but probably a misleading error message led to it, and then I didn't question it later...

**Pull request merged**
